function(add_nnet_test NAME)
  get_filename_component(ABSOLUTE_PATH ${NAME}.cpp ABSOLUTE)
  if (EXISTS ${ABSOLUTE_PATH})
    message(STATUS "Adding neural network test: ${NAME}.cpp")
  else()
    message(SEND_ERROR "${ABSOLUTE_PATH} does not exist")
    return()
  endif()

  add_executable(${NAME} ${NAME}.cpp)
  set_compile_options(${NAME})
  target_link_libraries(${NAME} PRIVATE nnet::nnet)
  target_link_libraries(${NAME} PRIVATE gtest gtest_main)
endfunction()

function (add_nnet_benchmark NAME)
  get_filename_component(ABSOLUTE_PATH ${NAME}.cpp ABSOLUTE)
  if (EXISTS ${ABSOLUTE_PATH})
    message(STATUS "Adding neural network benchmark: ${NAME}.cpp")
  else()
    message(SEND_ERROR "${ABSOLUTE_PATH} does not exist")
    return()
  endif()

  add_executable(${NAME} ${NAME}.cpp)
  set_compile_options(${NAME})
  target_link_libraries(${NAME} PRIVATE nnet::nnet)
endfunction()
